### ISSUE TITLE
Features for V12

### ISSUE THREAD

**Issue by FabianGosebrink** [damienbod/angular-auth-oidc-client#1050]
V12 will be developed on this branch: [ReleaseV12-WIP](https://github.com/damienbod/angular-auth-oidc-client/tree/releaseV12-WIP)

Gathering all Issues and PRs which will be done in V12 and maybe are breaking changes

- [x] Issue: Configuration via forRoot(...) method https://github.com/damienbod/angular-auth-oidc-client/issues/747 | PR https://github.com/damienbod/angular-auth-oidc-client/pull/1041
- [x] Issue: Remove the "AuthorizedState" enum in Version 12 https://github.com/damienbod/angular-auth-oidc-client/issues/755 | PR https://github.com/damienbod/angular-auth-oidc-client/pull/1062
- [x] Issue: Use a different key than redirect to store redirect route when using autologin https://github.com/damienbod/angular-auth-oidc-client/issues/1060 | PR #1067
- [x] Issue: Returnvalue of loginwithpopup and login should be the same https://github.com/damienbod/angular-auth-oidc-client/issues/1048 | PR https://github.com/damienbod/angular-auth-oidc-client/pull/1066
- [x] Issue: How to provide client id during logoff https://github.com/damienbod/angular-auth-oidc-client/issues/932 | PR https://github.com/damienbod/angular-auth-oidc-client/pull/1069
- [x] Issue: urlHandler callback function parameter in LogoffRevocationService.logoff does nothing https://github.com/damienbod/angular-auth-oidc-client/issues/966 | PR https://github.com/damienbod/angular-auth-oidc-client/pull/1069
- [x] Issue: Convert all instances of "Authorized" to "Authenticated" https://github.com/damienbod/angular-auth-oidc-client/issues/1088 | PR https://github.com/damienbod/angular-auth-oidc-client/pull/1085
- [x] Issue: Support for multiple APIs with unique scopes https://github.com/damienbod/angular-auth-oidc-client/issues/885 | PR https://github.com/damienbod/angular-auth-oidc-client/pull/1085
- [x] Issue: Multiple access tokens for the same client_id but different scopes https://github.com/damienbod/angular-auth-oidc-client/issues/620 | PR https://github.com/damienbod/angular-auth-oidc-client/pull/1085
- [x] Issue: Is there a silent renew event？#1011 | PR https://github.com/damienbod/angular-auth-oidc-client/pull/1085
- [x] Issue: Angular 12 Support https://github.com/damienbod/angular-auth-oidc-client/issues/1096 | PR: https://github.com/damienbod/angular-auth-oidc-client/pull/1112
- [x] Testing & Coverage
- [x] Improve documentation
- [x] Issue: Add configuration to disable or enable id_token expired check https://github.com/damienbod/angular-auth-oidc-client/issues/1113
- [x] Issue: Support for Azure B2C multiple policies https://github.com/damienbod/angular-auth-oidc-client/issues/802 | PR https://github.com/damienbod/angular-auth-oidc-client/pull/1085
- [x] Issue: Improve AutoLoginSample https://github.com/damienbod/angular-auth-oidc-client/issues/1138
- [x] Accessing AuthResult response object https://github.com/damienbod/angular-auth-oidc-client/issues/536
- [x] rename stsServer configuration parameter to authority
- [x] https://github.com/damienbod/angular-auth-oidc-client/issues/1164 | 
## 12.x
Issue: How to change configuration at runtime ? https://github.com/damienbod/angular-auth-oidc-client/issues/923
Issue: Error handling support for better user experience https://github.com/damienbod/angular-auth-oidc-client/issues/976

**Comment by julien-von-oetinger** [comment]
Hi,

Will this V12 support Angular 12 too ? I have tried to update my project to angular 12 and I have dependencies issues now.

**Comment by damienbod** [comment]
Hi @julien-von-oetinger yes.

For the moment you could just do a force update

Don't know why the breaking changes in V12 cause update problems but I was able to fix the peer dependencies by using force

```
ng update --force
```

**Comment by julien-von-oetinger** [comment]
Ok i'll try with force update.

For information, that's the error message I got:

`
npm ERR! Found: @angular/common@12.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~12.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.0.5" from angular-auth-oidc-client@11.6.9
npm ERR! node_modules/angular-auth-oidc-client
npm ERR!   angular-auth-oidc-client@"^11.6.9" from the root project
`

**Comment by FabianGosebrink** [comment]
We will address this, the lib will be V12 compatible. Please do not use this issue for Angular V12. This is V12 of _this lib_. But we are planning the compatibility of course. Make sure ngcc has run through the lib after installing it.

**Comment by damienbod** [comment]
party :) thanks for all the contributions, we are feature complete for Version 12

**Comment by piechpatrick** [comment]
When can we expect release v12?

**Comment by damienbod** [comment]
Hopefully soon. We discovered an issue when testing and doing the migration tests.

**Only one returntype (object) when subscribing to isAuthenticated and userdata to avoid confusion** #1164 

So we must fix this first and do the testing again. @FabianGosebrink needs to finish the PR, then testing and we're ready to release.

**Comment by FabianGosebrink** [comment]
It's done when it's done. But we're close. Planning to do some work on it today. See how far I come.

**Comment by damienbod** [comment]
released, thanks for all the support
